import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import { ToastContainer } from'react-toastify';
const roboto = Roboto({ subsets: ["latin"],weight:"500" });

export const metadata: Metadata = {
  title: "Thread",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={roboto.className}>
      <ToastContainer/>
        {children}
      </body>
    </html>
  );
}
